server:
  port: 80

spring:
  cloud:
    # 配置网关
    gateway:
      # 配置跨域请求
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*" #允许请求的资源
            allowedMethods: "*" #允许请求的方式
            allowedHeaders: "*" #允许所有请求的头
            allowCredentials: true #允许请求携带证书
      # 配置路由
      routes:
        - id: product_route
          # 路由转发地址  lb代表负载均衡
          uri: lb://service-product
          # 断言  匹配规则
          predicates:
            # 根据请求路径匹配
            - Path=/admin/product/**
        - id: user_route
          uri: lb://service-user
          predicates:
            - Path=/api/user/**


        - id: item_route
          uri: lb://service-item
          predicates:
            - Path=/api/inner/rpc/item/**

        - id: cart_route
          uri: lb://service-cart
          predicates:
            - Path=/api/cart/**

        - id: order_route
          uri: lb://service-order
          predicates:
            - Path=/api/order/**

        - id: payment_route
          uri: lb://service-payment
          predicates:
            - Path=/api/payment/**

        - id: seckill_route
          uri: lb://service-seckill
          predicates:
            - Path=/api/activity/**

        - id: weball_route
          uri: lb://web-all
          predicates:
            - Host=**.gmall.com,gmall.com



# 公共抽取到zipkin.yaml发布在排至中心
#spring:
#  # 采样的频率 默认是10%
#  sleuth:
#    sampler:
#      rate: 100
#  zipkin:
#    base-url: http://192.168.11.10:9411/ #链路追踪地址
#    # 采样发送给zipkin的方式,http请求
#    sender:
#      type: web
app:
  auth:
    no-auth-url:
      - /js/**
      - /css/**
      - /data/**
      - /fonts/**
      - /img/**
    deny-url:
      - /api/inner/**
    auth-url:
      - /order/**
      - /**/auth/**
      - /trade.html
      - /pay.html
    login-page: http://passport.gmall.com/login.html

