server:
  port: 8000

spring:
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

feign:
  client:
    config:
      service-item:
        read-timeout: 3000
        connect-timeout: 1000


