server:
  port: 10000

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.11.10:3306/gmall_user?useSSL=false
    username: root
    password: 131421
    driver-class-name: com.mysql.jdbc.Driver